//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebasEscuela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        public Alumno()
        {
            this.escuela1 = new HashSet<escuela>();
            this.profesor = new HashSet<profesor>();
        }
    [Display(Name ="id")]
        public int id { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Display(Name = "IdProfesor")]
        public int idProfesor { get; set; }
        [Display(Name = "IdEscuela")]
        public int idEscuela { get; set; }
    
        public virtual escuela escuela { get; set; }
        public virtual ICollection<escuela> escuela1 { get; set; }
        public virtual ICollection<profesor> profesor { get; set; }
    }
}
