//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebasEscuela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class escuela
    {
        public escuela()
        {
            this.Alumno = new HashSet<Alumno>();
            this.profesor1 = new HashSet<profesor>();
        }
        [Display(Name = "id")]
        public int id { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }
        [Display(Name = "idAlumno")]
        public int idAlumno { get; set; }
        [Display(Name = "idProfesor")]
        public int idProfesor { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual Alumno Alumno1 { get; set; }
        public virtual profesor profesor { get; set; }
        public virtual ICollection<profesor> profesor1 { get; set; }
    }
}
