//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebasEscuela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profesor
    {
        public profesor()
        {
            this.escuela = new HashSet<escuela>();
        }
        [Display(Name = "id")]
        public int id { get; set; }
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Display(Name = "idAlumno")]
        public Nullable<int> idAlumno { get; set; }
        [Display(Name = "idEscuela")]
        public Nullable<int> idEscuela { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual ICollection<escuela> escuela { get; set; }
        public virtual escuela escuela1 { get; set; }
    }
}
